name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build
      - run: npm run lint-check
      - run: npm run format-check

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ctrf-report
          path: ctrf/ctrf-report.json
